<?php
/**	op-unit-database-testcase:/index.php
 *
 * @created    2025-11-28
 * @package    op-unit-database-testcase
 * @copyright  2025 Tomoaki Nagahara All Rights Reserved.
 */

/**	Declare strict type
 *
 */
declare(strict_types=1);

/**	Namespace
 *
 */
namespace OP;

//	...
?>
<section class="index">
	<h1>Index</h1>
	<ul>
		<li>
			<a href="Communication">Communication</a> :
			<span data-translation="true">Connect to the database using raw PHP functions without using the ONEPIECE framework functions.</span>
		</li>
		<li>
			<a href="DML">DML</a> :
			<span data-translation="true">Manipulate data in a database.</span>
		</li>
	</ul>
</section>
